FROM golang:1.23.1-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/webUI ./cmd/webUI/main.go

FROM scratch

WORKDIR /app

COPY --from=builder /app/inputConvert /app/inputConvert

EXPOSE 8080

CMD ["/app/inputConvert"]