// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: internal/proto/inputconvert.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InputConvertService_UploadAndConvertExcelData_FullMethodName = "/api.InputConvertService/UploadAndConvertExcelData"
	InputConvertService_GetJobStatus_FullMethodName              = "/api.InputConvertService/GetJobStatus"
)

// InputConvertServiceClient is the client API for InputConvertService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InputConvertServiceClient interface {
	UploadAndConvertExcelData(ctx context.Context, in *UploadAndConvertExcelDataRequest, opts ...grpc.CallOption) (*UploadAndConvertExcelDataResponse, error)
	GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error)
}

type inputConvertServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInputConvertServiceClient(cc grpc.ClientConnInterface) InputConvertServiceClient {
	return &inputConvertServiceClient{cc}
}

func (c *inputConvertServiceClient) UploadAndConvertExcelData(ctx context.Context, in *UploadAndConvertExcelDataRequest, opts ...grpc.CallOption) (*UploadAndConvertExcelDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadAndConvertExcelDataResponse)
	err := c.cc.Invoke(ctx, InputConvertService_UploadAndConvertExcelData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inputConvertServiceClient) GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobStatusResponse)
	err := c.cc.Invoke(ctx, InputConvertService_GetJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InputConvertServiceServer is the server API for InputConvertService service.
// All implementations must embed UnimplementedInputConvertServiceServer
// for forward compatibility.
type InputConvertServiceServer interface {
	UploadAndConvertExcelData(context.Context, *UploadAndConvertExcelDataRequest) (*UploadAndConvertExcelDataResponse, error)
	GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error)
	mustEmbedUnimplementedInputConvertServiceServer()
}

// UnimplementedInputConvertServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInputConvertServiceServer struct{}

func (UnimplementedInputConvertServiceServer) UploadAndConvertExcelData(context.Context, *UploadAndConvertExcelDataRequest) (*UploadAndConvertExcelDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadAndConvertExcelData not implemented")
}
func (UnimplementedInputConvertServiceServer) GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedInputConvertServiceServer) mustEmbedUnimplementedInputConvertServiceServer() {}
func (UnimplementedInputConvertServiceServer) testEmbeddedByValue()                             {}

// UnsafeInputConvertServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InputConvertServiceServer will
// result in compilation errors.
type UnsafeInputConvertServiceServer interface {
	mustEmbedUnimplementedInputConvertServiceServer()
}

func RegisterInputConvertServiceServer(s grpc.ServiceRegistrar, srv InputConvertServiceServer) {
	// If the following call pancis, it indicates UnimplementedInputConvertServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InputConvertService_ServiceDesc, srv)
}

func _InputConvertService_UploadAndConvertExcelData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadAndConvertExcelDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InputConvertServiceServer).UploadAndConvertExcelData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InputConvertService_UploadAndConvertExcelData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InputConvertServiceServer).UploadAndConvertExcelData(ctx, req.(*UploadAndConvertExcelDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InputConvertService_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InputConvertServiceServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InputConvertService_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InputConvertServiceServer).GetJobStatus(ctx, req.(*GetJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InputConvertService_ServiceDesc is the grpc.ServiceDesc for InputConvertService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InputConvertService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.InputConvertService",
	HandlerType: (*InputConvertServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadAndConvertExcelData",
			Handler:    _InputConvertService_UploadAndConvertExcelData_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _InputConvertService_GetJobStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/inputconvert.proto",
}
