// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: internal/proto/inputconvert.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetJobStatusResponse_JobStatus int32

const (
	GetJobStatusResponse_PENDING    GetJobStatusResponse_JobStatus = 0
	GetJobStatusResponse_PROCESSING GetJobStatusResponse_JobStatus = 1
	GetJobStatusResponse_COMPLETED  GetJobStatusResponse_JobStatus = 2
	GetJobStatusResponse_FAILED     GetJobStatusResponse_JobStatus = 3
)

// Enum value maps for GetJobStatusResponse_JobStatus.
var (
	GetJobStatusResponse_JobStatus_name = map[int32]string{
		0: "PENDING",
		1: "PROCESSING",
		2: "COMPLETED",
		3: "FAILED",
	}
	GetJobStatusResponse_JobStatus_value = map[string]int32{
		"PENDING":    0,
		"PROCESSING": 1,
		"COMPLETED":  2,
		"FAILED":     3,
	}
)

func (x GetJobStatusResponse_JobStatus) Enum() *GetJobStatusResponse_JobStatus {
	p := new(GetJobStatusResponse_JobStatus)
	*p = x
	return p
}

func (x GetJobStatusResponse_JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetJobStatusResponse_JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_inputconvert_proto_enumTypes[0].Descriptor()
}

func (GetJobStatusResponse_JobStatus) Type() protoreflect.EnumType {
	return &file_internal_proto_inputconvert_proto_enumTypes[0]
}

func (x GetJobStatusResponse_JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetJobStatusResponse_JobStatus.Descriptor instead.
func (GetJobStatusResponse_JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_inputconvert_proto_rawDescGZIP(), []int{3, 0}
}

type UploadAndConvertExcelDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAndConvertExcelDataRequest) Reset() {
	*x = UploadAndConvertExcelDataRequest{}
	mi := &file_internal_proto_inputconvert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAndConvertExcelDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAndConvertExcelDataRequest) ProtoMessage() {}

func (x *UploadAndConvertExcelDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_inputconvert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAndConvertExcelDataRequest.ProtoReflect.Descriptor instead.
func (*UploadAndConvertExcelDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_inputconvert_proto_rawDescGZIP(), []int{0}
}

func (x *UploadAndConvertExcelDataRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *UploadAndConvertExcelDataRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type UploadAndConvertExcelDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // ID for tracking the conversion job
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`          // Optional success message
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`              // Optional error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAndConvertExcelDataResponse) Reset() {
	*x = UploadAndConvertExcelDataResponse{}
	mi := &file_internal_proto_inputconvert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAndConvertExcelDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAndConvertExcelDataResponse) ProtoMessage() {}

func (x *UploadAndConvertExcelDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_inputconvert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAndConvertExcelDataResponse.ProtoReflect.Descriptor instead.
func (*UploadAndConvertExcelDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_inputconvert_proto_rawDescGZIP(), []int{1}
}

func (x *UploadAndConvertExcelDataResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *UploadAndConvertExcelDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadAndConvertExcelDataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_internal_proto_inputconvert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_inputconvert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_inputconvert_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobStatusResponse struct {
	state    protoimpl.MessageState         `protogen:"open.v1"`
	Status   GetJobStatusResponse_JobStatus `protobuf:"varint,1,opt,name=status,proto3,enum=api.GetJobStatusResponse_JobStatus" json:"status,omitempty"`
	Progress int32                          `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"` // Percentage of completion (0-100)
	Message       string                         `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`    // Optional status message (e.g., "Reading file", "Validating data")
	Error         string                         `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`        // Optional error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_internal_proto_inputconvert_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_inputconvert_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_inputconvert_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobStatusResponse) GetStatus() GetJobStatusResponse_JobStatus {
	if x != nil {
		return x.Status
	}
	return GetJobStatusResponse_PENDING
}

func (x *GetJobStatusResponse) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *GetJobStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetJobStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_proto_inputconvert_proto protoreflect.FileDescriptor

const file_internal_proto_inputconvert_proto_rawDesc = "" +
	"\n" +
	"!internal/proto/inputconvert.proto\x12\x03api\"[\n" +
	" UploadAndConvertExcelDataRequest\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"j\n" +
	"!UploadAndConvertExcelDataResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xe4\x01\n" +
	"\x14GetJobStatusResponse\x12;\n" +
	"\x06status\x18\x01 \x01(\x0e2#.api.GetJobStatusResponse.JobStatusR\x06status\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"C\n" +
	"\tJobStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x032\xca\x01\n" +
	"\x13InputConvertService\x12l\n" +
	"\x19UploadAndConvertExcelData\x12%.api.UploadAndConvertExcelDataRequest\x1a&.api.UploadAndConvertExcelDataResponse\"\x00\x12E\n" +
	"\fGetJobStatus\x12\x18.api.GetJobStatusRequest\x1a\x19.api.GetJobStatusResponse\"\x00B#Z!github.com/saintecroix/diplom/apib\x06proto3"

var (
	file_internal_proto_inputconvert_proto_rawDescOnce sync.Once
	file_internal_proto_inputconvert_proto_rawDescData []byte
)

func file_internal_proto_inputconvert_proto_rawDescGZIP() []byte {
	file_internal_proto_inputconvert_proto_rawDescOnce.Do(func() {
		file_internal_proto_inputconvert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_inputconvert_proto_rawDesc), len(file_internal_proto_inputconvert_proto_rawDesc)))
	})
	return file_internal_proto_inputconvert_proto_rawDescData
}

var file_internal_proto_inputconvert_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_inputconvert_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_proto_inputconvert_proto_goTypes = []any{
	(GetJobStatusResponse_JobStatus)(0),       // 0: api.GetJobStatusResponse.JobStatus
	(*UploadAndConvertExcelDataRequest)(nil),  // 1: api.UploadAndConvertExcelDataRequest
	(*UploadAndConvertExcelDataResponse)(nil), // 2: api.UploadAndConvertExcelDataResponse
	(*GetJobStatusRequest)(nil),               // 3: api.GetJobStatusRequest
	(*GetJobStatusResponse)(nil),              // 4: api.GetJobStatusResponse
}
var file_internal_proto_inputconvert_proto_depIdxs = []int32{
	0, // 0: api.GetJobStatusResponse.status:type_name -> api.GetJobStatusResponse.JobStatus
	1, // 1: api.InputConvertService.UploadAndConvertExcelData:input_type -> api.UploadAndConvertExcelDataRequest
	3, // 2: api.InputConvertService.GetJobStatus:input_type -> api.GetJobStatusRequest
	2, // 3: api.InputConvertService.UploadAndConvertExcelData:output_type -> api.UploadAndConvertExcelDataResponse
	4, // 4: api.InputConvertService.GetJobStatus:output_type -> api.GetJobStatusResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_inputconvert_proto_init() }
func file_internal_proto_inputconvert_proto_init() {
	if File_internal_proto_inputconvert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_inputconvert_proto_rawDesc), len(file_internal_proto_inputconvert_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_inputconvert_proto_goTypes,
		DependencyIndexes: file_internal_proto_inputconvert_proto_depIdxs,
		EnumInfos:         file_internal_proto_inputconvert_proto_enumTypes,
		MessageInfos:      file_internal_proto_inputconvert_proto_msgTypes,
	}.Build()
	File_internal_proto_inputconvert_proto = out.File
	file_internal_proto_inputconvert_proto_goTypes = nil
	file_internal_proto_inputconvert_proto_depIdxs = nil
}
