// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/inputconvert.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConvertExcelDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertExcelDataRequest) Reset() {
	*x = ConvertExcelDataRequest{}
	mi := &file_proto_inputconvert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertExcelDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertExcelDataRequest) ProtoMessage() {}

func (x *ConvertExcelDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inputconvert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertExcelDataRequest.ProtoReflect.Descriptor instead.
func (*ConvertExcelDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_inputconvert_proto_rawDescGZIP(), []int{0}
}

func (x *ConvertExcelDataRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type ConvertExcelDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []string               `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertExcelDataResponse) Reset() {
	*x = ConvertExcelDataResponse{}
	mi := &file_proto_inputconvert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertExcelDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertExcelDataResponse) ProtoMessage() {}

func (x *ConvertExcelDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inputconvert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertExcelDataResponse.ProtoReflect.Descriptor instead.
func (*ConvertExcelDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_inputconvert_proto_rawDescGZIP(), []int{1}
}

func (x *ConvertExcelDataResponse) GetResults() []string {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ConvertExcelDataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_inputconvert_proto protoreflect.FileDescriptor

const file_proto_inputconvert_proto_rawDesc = "" +
	"\n" +
	"\x18proto/inputconvert.proto\x12\finputconvert\"6\n" +
	"\x17ConvertExcelDataRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"J\n" +
	"\x18ConvertExcelDataResponse\x12\x18\n" +
	"\aresults\x18\x01 \x03(\tR\aresults\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2z\n" +
	"\x13InputConvertService\x12c\n" +
	"\x10ConvertExcelData\x12%.inputconvert.ConvertExcelDataRequest\x1a&.inputconvert.ConvertExcelDataResponse\"\x00B%Z#github.com/saintecroix/diplom/protob\x06proto3"

var (
	file_proto_inputconvert_proto_rawDescOnce sync.Once
	file_proto_inputconvert_proto_rawDescData []byte
)

func file_proto_inputconvert_proto_rawDescGZIP() []byte {
	file_proto_inputconvert_proto_rawDescOnce.Do(func() {
		file_proto_inputconvert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inputconvert_proto_rawDesc), len(file_proto_inputconvert_proto_rawDesc)))
	})
	return file_proto_inputconvert_proto_rawDescData
}

var file_proto_inputconvert_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_inputconvert_proto_goTypes = []any{
	(*ConvertExcelDataRequest)(nil),  // 0: inputconvert.ConvertExcelDataRequest
	(*ConvertExcelDataResponse)(nil), // 1: inputconvert.ConvertExcelDataResponse
}
var file_proto_inputconvert_proto_depIdxs = []int32{
	0, // 0: inputconvert.InputConvertService.ConvertExcelData:input_type -> inputconvert.ConvertExcelDataRequest
	1, // 1: inputconvert.InputConvertService.ConvertExcelData:output_type -> inputconvert.ConvertExcelDataResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_inputconvert_proto_init() }
func file_proto_inputconvert_proto_init() {
	if File_proto_inputconvert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inputconvert_proto_rawDesc), len(file_proto_inputconvert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inputconvert_proto_goTypes,
		DependencyIndexes: file_proto_inputconvert_proto_depIdxs,
		MessageInfos:      file_proto_inputconvert_proto_msgTypes,
	}.Build()
	File_proto_inputconvert_proto = out.File
	file_proto_inputconvert_proto_goTypes = nil
	file_proto_inputconvert_proto_depIdxs = nil
}
