// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: inputconvert.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InputConvertService_ConvertExcelData_FullMethodName = "/api.InputConvertService/ConvertExcelData"
)

// InputConvertServiceClient is the client API for InputConvertService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InputConvertServiceClient interface {
	ConvertExcelData(ctx context.Context, in *ConvertExcelDataRequest, opts ...grpc.CallOption) (*ConvertExcelDataResponse, error)
}

type inputConvertServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInputConvertServiceClient(cc grpc.ClientConnInterface) InputConvertServiceClient {
	return &inputConvertServiceClient{cc}
}

func (c *inputConvertServiceClient) ConvertExcelData(ctx context.Context, in *ConvertExcelDataRequest, opts ...grpc.CallOption) (*ConvertExcelDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertExcelDataResponse)
	err := c.cc.Invoke(ctx, InputConvertService_ConvertExcelData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InputConvertServiceServer is the server API for InputConvertService service.
// All implementations must embed UnimplementedInputConvertServiceServer
// for forward compatibility.
type InputConvertServiceServer interface {
	ConvertExcelData(context.Context, *ConvertExcelDataRequest) (*ConvertExcelDataResponse, error)
	mustEmbedUnimplementedInputConvertServiceServer()
}

// UnimplementedInputConvertServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInputConvertServiceServer struct{}

func (UnimplementedInputConvertServiceServer) ConvertExcelData(context.Context, *ConvertExcelDataRequest) (*ConvertExcelDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertExcelData not implemented")
}
func (UnimplementedInputConvertServiceServer) mustEmbedUnimplementedInputConvertServiceServer() {}
func (UnimplementedInputConvertServiceServer) testEmbeddedByValue()                             {}

// UnsafeInputConvertServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InputConvertServiceServer will
// result in compilation errors.
type UnsafeInputConvertServiceServer interface {
	mustEmbedUnimplementedInputConvertServiceServer()
}

func RegisterInputConvertServiceServer(s grpc.ServiceRegistrar, srv InputConvertServiceServer) {
	// If the following call pancis, it indicates UnimplementedInputConvertServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InputConvertService_ServiceDesc, srv)
}

func _InputConvertService_ConvertExcelData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertExcelDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InputConvertServiceServer).ConvertExcelData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InputConvertService_ConvertExcelData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InputConvertServiceServer).ConvertExcelData(ctx, req.(*ConvertExcelDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InputConvertService_ServiceDesc is the grpc.ServiceDesc for InputConvertService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InputConvertService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.InputConvertService",
	HandlerType: (*InputConvertServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertExcelData",
			Handler:    _InputConvertService_ConvertExcelData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inputconvert.proto",
}
